name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Playwright test container
        run: docker build -t vibe-playwright-tests .

      - name: Run Playwright tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}/playwright-report:/app/playwright-report vibe-playwright-tests

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
